/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */



GtkWidget* create_window1 (void);
GtkWidget* create_dialog1_information (void);
GtkWidget* create_search_dialog (AD data);
GtkWidget *create_replace_dialog (AD data); // 建立取代dialog 

GtkWidget* create_file_chooser_oepn_dialog (GtkWidget *window); // 建立開啟檔案的dialog 
GtkWidget* create_file_chooser_save_dialog (GtkWidget *window); // 建立儲存檔案的dialog  
