/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
  
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h> 
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gtk/gtk.h>
#include <glib.h>

#include "support.h"  


 

 

gchar *utf8( const char *str )
// 解決無法顯示中文的窘境
{
  return g_locale_to_utf8( str, -1, NULL, NULL, NULL);
}

gchar *fromUtf8( const char *str )
{
  return g_locale_from_utf8 (str, -1, NULL, NULL, NULL);
}


void replace (GtkTextView *text_view, const gchar *text, const gchar *replaceText, GtkTextIter *iter)
// 取代主函式 
{
  GtkTextIter mstart, mend; 
  GtkTextBuffer *buffer;
  gboolean found;
  GtkTextMark *last_pos;
  GtkClipboard *clipboard;

  buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (text_view));
  found = gtk_text_iter_forward_search (iter, text, 0, &mstart, &mend, NULL);

  if (found)
  {
    clipboard = gtk_clipboard_get( GDK_NONE ); // 取得反白選取的部份
    
    
    gtk_text_buffer_cut_clipboard (buffer, clipboard, TRUE); // 剪下選取的反白字串 
    gtk_clipboard_set_text (clipboard, replaceText, -1); // 將剪貼簿修改為replaceText 
    
    
    gtk_text_buffer_select_range (buffer, &mstart, &mend);
    last_pos = gtk_text_buffer_create_mark (buffer, "last_pos", &mend, FALSE); // 註記起來 之後才可往下搜尋 
      
    gtk_text_view_scroll_mark_onscreen(text_view, last_pos); // 移動捲軸 可追蹤目前搜尋的位置 
    
    gtk_text_buffer_paste_clipboard (buffer, clipboard, &mend, TRUE); // 將剪貼簿的內容貼到指定區域 
    
  }
}


gboolean find (GtkTextView *text_view, const gchar *text, GtkTextIter *iter)
// 搜尋主函式 
{
  GtkTextIter mstart, mend;
  GtkTextBuffer *buffer;
  gboolean found;
  GtkTextMark *last_pos;

  buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (text_view));
  found = gtk_text_iter_forward_search (iter, text, 0, &mstart, &mend, NULL);

  if (found)
  {
    gtk_text_buffer_select_range (buffer, &mstart, &mend);
    last_pos = gtk_text_buffer_create_mark (buffer, "last_pos", &mend, FALSE); // 註記起來 之後才可往下搜尋 
      
    gtk_text_view_scroll_mark_onscreen(text_view, last_pos); // 移動捲軸 可追蹤目前搜尋的位置 
  }
  
  return found ;
}



void 
open_file(gchar *filename, GtkTextView *textView) 
// 開啟文件檔並顯示在textview上
// 目前瓶頸：無法開啟UTF-16編碼的文件
{
  gchar *content, *content2, *ascii2utf8; 
  gsize bytes, bytes_read, bytes_written;
  GError *error = NULL; 
  GtkTextBuffer *buffer; 
  
  buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW (textView));
    
  g_file_get_contents (filename, &content, &bytes, &error);
   
  //g_file_set_contents ("TEST.txt", content, bytes, &error);
  //g_convert (content, -1, "UTF-16", "UTF-8", NULL, NULL, &error);
  
  ascii2utf8 = g_locale_to_utf8( content, -1, NULL, NULL, &error);
  
  if (error) // 若不能轉換，代表原本就是utf-8了 
    gtk_text_buffer_set_text (buffer, content, -1); // 用來開UTF-8文件   
  else
    gtk_text_buffer_set_text (buffer, ascii2utf8, -1); // 用來開ANSI文件 
  
  free (content);
  free (ascii2utf8);
}

void  save_to_file(gchar *filename, GtkTextView *textView)
// 將緩衝區的文字儲存到名為filename的檔案裡 
{
  gchar *content; 
  gsize bytes;
  GError *error = NULL;
  GtkTextBuffer *buffer;
  GtkTextIter start, end;
  
  buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (textView));

  gtk_text_buffer_get_bounds (GTK_TEXT_BUFFER (buffer), &start, &end);/*取得開始和結束位置的Iter*/


  content = gtk_text_buffer_get_text (GTK_TEXT_BUFFER (buffer), &start, &end, FALSE);/*取得整份文字資料*/
   
  g_file_set_contents (filename, content, -1, &error);
  
  
}




// ================以下為本來有的============== 

GtkWidget*
lookup_widget                          (GtkWidget       *widget,
                                        const gchar     *widget_name)
{
  GtkWidget *parent, *found_widget;

  for (;;)
    {
      if (GTK_IS_MENU (widget))
        parent = gtk_menu_get_attach_widget (GTK_MENU (widget));
      else
        parent = widget->parent;
      if (!parent)
        parent = (GtkWidget*) g_object_get_data (G_OBJECT (widget), "GladeParentKey");
      if (parent == NULL)
        break;
      widget = parent;
    }

  found_widget = (GtkWidget*) g_object_get_data (G_OBJECT (widget),
                                                 widget_name);
  if (!found_widget)
    g_warning ("Widget not found: %s", widget_name);
  return found_widget;
}

static GList *pixmaps_directories = NULL;

/* Use this function to set the directory containing installed pixmaps. */
void
add_pixmap_directory                   (const gchar     *directory)
{
  pixmaps_directories = g_list_prepend (pixmaps_directories,
                                        g_strdup (directory));
}

/* This is an internally used function to find pixmap files. */
static gchar*
find_pixmap_file                       (const gchar     *filename)
{
  GList *elem;

  /* We step through each of the pixmaps directory to find it. */
  elem = pixmaps_directories;
  while (elem)
    {
      gchar *pathname = g_strdup_printf ("%s%s%s", (gchar*)elem->data,
                                         G_DIR_SEPARATOR_S, filename);
      if (g_file_test (pathname, G_FILE_TEST_EXISTS))
        return pathname;
      g_free (pathname);
      elem = elem->next;
    }
  return NULL;
}

/* This is an internally used function to create pixmaps. */
GtkWidget*
create_pixmap                          (GtkWidget       *widget,
                                        const gchar     *filename)
{
  gchar *pathname = NULL;
  GtkWidget *pixmap;

  if (!filename || !filename[0])
      return gtk_image_new ();

  pathname = find_pixmap_file (filename);

  if (!pathname)
    {
      g_warning (_("Couldn't find pixmap file: %s"), filename);
      return gtk_image_new ();
    }

  pixmap = gtk_image_new_from_file (pathname);
  g_free (pathname);
  return pixmap;
}

/* This is an internally used function to create pixmaps. */
GdkPixbuf*
create_pixbuf                          (const gchar     *filename)
{
  gchar *pathname = NULL;
  GdkPixbuf *pixbuf;
  GError *error = NULL;

  if (!filename || !filename[0])
      return NULL;

  pathname = find_pixmap_file (filename);

  if (!pathname)
    {
      g_warning (_("Couldn't find pixmap file: %s"), filename);
      return NULL;
    }

  pixbuf = gdk_pixbuf_new_from_file (pathname, &error);
  if (!pixbuf)
    {
      fprintf (stderr, "Failed to load pixbuf file: %s: %s\n",
               pathname, error->message);
      g_error_free (error);
    }
  g_free (pathname);
  return pixbuf;
}

/* This is used to set ATK action descriptions. */
void
glade_set_atk_action_description       (AtkAction       *action,
                                        const gchar     *action_name,
                                        const gchar     *description)
{
  gint n_actions, i;

  n_actions = atk_action_get_n_actions (action);
  for (i = 0; i < n_actions; i++)
    {
      if (!strcmp (atk_action_get_name (action, i), action_name))
        atk_action_set_description (action, i, description);
    }
}


